import type { Task, UserProfile, Review, CreditsTransaction } from 'shared'

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'u1',
    name: 'Maria Santos',
    avatar_url: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Maria',
    bio: 'Retired teacher from the Dominican Republic. Love helping my neighbors!',
    neighborhood: 'Jackson Heights',
    borough: 'Queens',
    credits_balance: 145,
    trust_level: 'trusted',
    rating_avg: 4.9,
    rating_count: 34,
    tasks_completed: 28,
    tasks_posted: 12,
    languages: ['en', 'es'],
    is_id_verified: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'u2',
    name: 'James Park',
    avatar_url: 'https://api.dicebear.com/8.x/avataaars/svg?seed=James',
    bio: 'Software engineer. Great with tech problems. Happy to help!',
    neighborhood: 'Astoria',
    borough: 'Queens',
    credits_balance: 80,
    trust_level: 'established',
    rating_avg: 4.7,
    rating_count: 15,
    tasks_completed: 12,
    tasks_posted: 5,
    languages: ['en', 'ko'],
    is_id_verified: false,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'u3',
    name: 'Fatima Al-Hassan',
    avatar_url: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Fatima',
    bio: 'Community organizer. Here to connect neighbors and build trust.',
    neighborhood: 'Harlem',
    borough: 'Manhattan',
    credits_balance: 220,
    trust_level: 'verified',
    rating_avg: 5.0,
    rating_count: 52,
    tasks_completed: 47,
    tasks_posted: 20,
    languages: ['en', 'ar', 'fr'],
    is_id_verified: true,
    created_at: '2023-11-20T00:00:00Z',
  },
  {
    id: 'u4',
    name: 'Carlos Rivera',
    avatar_url: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Carlos',
    bio: 'Handyman and general helper. No job too small.',
    neighborhood: 'Sunnyside',
    borough: 'Queens',
    credits_balance: 60,
    trust_level: 'established',
    rating_avg: 4.6,
    rating_count: 21,
    tasks_completed: 18,
    tasks_posted: 8,
    languages: ['en', 'es'],
    is_id_verified: false,
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: 'u5',
    name: 'Mei Lin',
    avatar_url: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Mei',
    bio: 'Graduate student. Good at tutoring math and science!',
    neighborhood: 'Flushing',
    borough: 'Queens',
    credits_balance: 35,
    trust_level: 'new',
    rating_avg: 0,
    rating_count: 0,
    tasks_completed: 0,
    tasks_posted: 2,
    languages: ['en', 'zh'],
    is_id_verified: false,
    created_at: '2024-05-28T00:00:00Z',
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    creator_id: 'u3',
    creator: MOCK_USERS[2],
    title: 'Help carry groceries from C-Town to my apartment',
    description: 'I need help carrying 4-5 bags of groceries from C-Town on 125th to my 3rd floor walkup. Should take about 20 minutes. I am 72 years old and my back has been giving me trouble.',
    category: 'simple_help',
    required_trust_level: 'new',
    location: { lat: 40.8080, lng: -73.9480 },
    address: '125th St & Lexington Ave, Harlem',
    neighborhood: 'Harlem',
    borough: 'Manhattan',
    payment_type: 'credits',
    payment_amount: null,
    credits_amount: 10,
    status: 'open',
    applicant_count: 2,
    scheduled_for: null,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 't2',
    creator_id: 'u1',
    creator: MOCK_USERS[0],
    title: 'Fix my Wi-Fi router — keeps disconnecting',
    description: 'My internet keeps dropping every hour. I have a Xfinity router and I think it might need some settings changed. I have tried restarting it but it still happens.',
    category: 'tech_help',
    required_trust_level: 'established',
    location: { lat: 40.7484, lng: -73.9967 },
    address: 'Jackson Heights, Queens',
    neighborhood: 'Jackson Heights',
    borough: 'Queens',
    payment_type: 'cash',
    payment_amount: 15,
    credits_amount: null,
    status: 'open',
    applicant_count: 1,
    scheduled_for: null,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 't3',
    creator_id: 'u2',
    creator: MOCK_USERS[1],
    title: 'Dog walk — 30 min around Astoria Park',
    description: 'Need someone to walk my golden retriever, Max, for about 30 minutes around Astoria Park. He is very friendly and great with people. Morning or afternoon works.',
    category: 'pet_care',
    required_trust_level: 'new',
    location: { lat: 40.7721, lng: -73.9301 },
    address: 'Astoria Park, Queens',
    neighborhood: 'Astoria',
    borough: 'Queens',
    payment_type: 'credits',
    payment_amount: null,
    credits_amount: 15,
    status: 'open',
    applicant_count: 3,
    scheduled_for: null,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 't4',
    creator_id: 'u4',
    creator: MOCK_USERS[3],
    title: 'Help moving a couch up to 2nd floor',
    description: 'I need 2 people to help move a large sofa from a U-Haul truck to my 2nd floor apartment. There is an elevator. Should take 30-40 mins. I will have pizza ready!',
    category: 'moving',
    required_trust_level: 'established',
    location: { lat: 40.7447, lng: -73.9354 },
    address: 'Sunnyside, Queens',
    neighborhood: 'Sunnyside',
    borough: 'Queens',
    payment_type: 'exchange',
    payment_amount: null,
    credits_amount: null,
    status: 'open',
    applicant_count: 0,
    scheduled_for: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
  {
    id: 't5',
    creator_id: 'u3',
    creator: MOCK_USERS[2],
    title: 'Spanish to English translation for medical forms',
    description: 'My grandmother has some medical forms from Mount Sinai that need to be translated from Spanish to English. About 4 pages. Accuracy is important.',
    category: 'tutoring',
    required_trust_level: 'trusted',
    location: { lat: 40.7901, lng: -73.9526 },
    address: 'Harlem, Manhattan',
    neighborhood: 'Harlem',
    borough: 'Manhattan',
    payment_type: 'cash',
    payment_amount: 25,
    credits_amount: null,
    status: 'open',
    applicant_count: 1,
    scheduled_for: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 't6',
    creator_id: 'u5',
    creator: MOCK_USERS[4],
    title: 'Math tutoring for 8th grader — algebra',
    description: 'My younger brother is struggling with algebra. Need someone patient who can help him understand equations and graphing. 1 hour session, can be in person or video call.',
    category: 'tutoring',
    required_trust_level: 'established',
    location: { lat: 40.7676, lng: -73.8330 },
    address: 'Flushing, Queens',
    neighborhood: 'Flushing',
    borough: 'Queens',
    payment_type: 'credits',
    payment_amount: null,
    credits_amount: 20,
    status: 'open',
    applicant_count: 2,
    scheduled_for: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    task_id: 't1',
    reviewer_id: 'u3',
    reviewer: MOCK_USERS[2],
    reviewee_id: 'u1',
    rating: 5,
    comment: 'Maria was amazing! Very reliable and so kind. She even helped organize the bags.',
    created_at: '2024-04-10T00:00:00Z',
  },
  {
    id: 'r2',
    task_id: 't2',
    reviewer_id: 'u1',
    reviewer: MOCK_USERS[0],
    reviewee_id: 'u2',
    rating: 5,
    comment: 'James fixed my WiFi in 15 minutes. Super knowledgeable and patient explaining the issue.',
    created_at: '2024-04-20T00:00:00Z',
  },
  {
    id: 'r3',
    task_id: 't3',
    reviewer_id: 'u2',
    reviewer: MOCK_USERS[1],
    reviewee_id: 'u4',
    rating: 4,
    comment: 'Carlos was reliable and Max loved him! He kept me updated the whole time.',
    created_at: '2024-05-01T00:00:00Z',
  },
]

export const MOCK_TRANSACTIONS: CreditsTransaction[] = [
  {
    id: 'tr1',
    user_id: 'u1',
    amount: 20,
    type: 'bonus',
    description: 'Welcome bonus — thanks for joining Clutch!',
    task_id: null,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'tr2',
    user_id: 'u1',
    amount: 10,
    type: 'earned',
    description: 'Helped carry groceries for Fatima',
    task_id: 't1',
    created_at: '2024-04-10T00:00:00Z',
  },
  {
    id: 'tr3',
    user_id: 'u1',
    amount: -15,
    type: 'spent',
    description: 'Posted: Dog walk for Max',
    task_id: 't3',
    created_at: '2024-05-01T00:00:00Z',
  },
]
